---
- name: "WordPress Server: Install LEMP Stack with PHP 5.5 and MariaDB MySQL"
  hosts: web
  remote_user: root
  # sudo: yes

  roles:
    - common
    - mariadb
    - php-55
    - nginx
    - memcached
    - composer
    - dev-tools
    - wp-cli
    - capistrano-setup
    - wordpress-sites
